name: CI/CD with GithubAction
on:
  push:
    branches: [ master ]
    pull_request: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: compile project
        run: mvn compile
      - name: test the project
        run: mvn test
      - name: build the project
        run: mvn install
      - name: deploy the project
        run: echo "successfully deployed"
      - name: docker build and push
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: malonicester/spring-boot-github-actions
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#1.Login to docker
#2. Build a docker image
#3. Push the image to docker hub