name: CI/CD with GithubAction
on:
  push:
    branches: [ master ]
    pull_request: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: compile project
        run: mvn compile
      - name: test the project
        run: mvn test
      - name: build the project
        run: mvn install
      - name: deploy the project
        run: echo "successfully deployed"